### ISSUE TITLE
reading hls-lfcd-lds sensor on Ubuntu Laptop 16.04 with ROS Kinetic

### ISSUE THREAD

**Issue by HDallali** [ROBOTIS-GIT/hls_lfcd_lds_driver#18]
Hi,

I'm trying to read the LIDAR data from the hls_lfcd-lds sensor on my Ubuntu Laptop via the USB dev path /dev/ttyUSB0. The sensor comes with an adpater and can be plugged in to the computer using the USB port. 
I have Ubuntu 16.04, installed ROS Kinetic, and the has_lfcd_lds_driver and I can run the launch commands. The sensor is detected and start to turn but I don’t see the points in rviz. When running without rviz I don’t see the publisher’s data when typing roslist echo /scan. 

I was wondering if you could help me to find what's the issue?

Thank you,
Houman

**Comment by routiful** [comment]
Hi :)

Try below command before launch package

`sudo chmod a+rw /dev/ttyUSBx/`
(type a USB port number in 'x')

If it not working after that, show me how to set your environment by taking picture.
I wonder how to connect between sensor and pc.

Thanks
Darby

**Comment by HDallali** [comment]
Hi Darby,
Thanks for your message and sorry for my delay in getting back. I have tried the code you mentioned above with different USB port numbers (x) but only x=0 works and does not give an error. If I try a different port number it says 
chmod: cannot access '/dev/ttyUSB1': No such file or directory 
for x=1 and so on. I have tried this on several ubuntu laptops and all gave the same results.
would you please let me know if you mean the ros environment or the general ubuntu environment?
Thanks,
Houman

**Comment by robotpilot** [comment]
I think this is a simple connection problem. 
Haven't you solved this problem yet? If so, I'd like to try it together.

**Comment by HDallali** [comment]
Dear robotpilot,
Thanks for your message. I haven't solved this problem yet. I appreciate your advice.
