### ISSUE TITLE
RLException: [view_hlds_laser.launch] Cannot launch the program

### ISSUE THREAD

**Issue by anshulvj** [ROBOTIS-GIT/hls_lfcd_lds_driver#20]
So I followed the steps as given in the documentation:
1) Installed ROS first on my Ubuntu 16.04 64-bit
2) I compiled and installed the https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git, as well as executed the following commands
`sudo apt-get install ros-kinetic-hls-lfcd-lds-driver`
`sudo chmod a+rw /dev/ttyUSB0`

None of these steps had issues and ran successfully. However when I try to run
`roslaunch hls_lfcd_lds_driver hlds_laser.launch`
or 
`roslaunch hls_lfcd_lds_driver view_hlds_laser.launch`
it says
`RLException: [view_hlds_laser.launch] is neither a launch file in package [hls_lfcd_lds_driver] nor is [hls_lfcd_lds_driver] a launch file name
The traceback for the exception was written to the log file`

Not sure what's happening. Any ideas?

Thanks
Anshul

**Comment by robotpilot** [comment]
If there is a problem, I recommend that you download the source code and compile it like below.

```
$ cd ~/catkin_ws/src
$ git clone https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git
$ cd ~/catkin_ws && catkin_make
$ sudo chmod a+rw /dev/ttyUSB0
$ roslaunch hls_lfcd_lds_driver view_hlds_laser.launch
```

**Comment by robotpilot** [comment]
This issue will be closed since there was no actions for a while.
You can reopen this issue to show this issue to the users whenever.
