### ISSUE TITLE
The first byte is not 0xFA

### ISSUE THREAD

**Issue by pssp123** [ROBOTIS-GIT/hls_lfcd_lds_driver#32]
I power on the lidar and the motor of the lidar is on work.Then I run the driver.But the first byte is not 0xFA.It throws error "An exception was thrown: read: End of line" after several times.

**Comment by routiful** [comment]
Hi :)

Have you get the problem when you executed launch file we provide?? Or special development environment??
If you upload some image or copy and paste error messages on terminal window??

**Comment by pssp123** [comment]
Hi
I have tried using launch file which is provide by you,but the program is process die.As the picture.
PS:I have tried sending 'b' to laser, the motor can revolve and I can receive the data.So I can confirm the serial ID set correctly and computer make connect to the laser succeed.
![image](https://user-images.githubusercontent.com/23045104/43309085-5291a1a2-91b6-11e8-9849-acf105a42458.png)

**Comment by pssp123** [comment]
Hi
  I have tried canceling the command of start motor in the construct,and it pass the first byte verification  which is equal to 0xFA. 
  But the program still returns process die by End of file when it runs in boost::asio::read().I guess it read too fast.so I have tried adding usleep() before boost::asio::read().It is on work.But I don`t think it`s good way to solve this problem,because it takes a long time to receive a frame of scan data.

**Comment by routiful** [comment]
That's might be firmware problem. If you contact our customer service team(contactus2@robotis.com), they would inform to you how to exchange your lidar.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
