### ISSUE TITLE
An exception was thrown: read: End of file

### ISSUE THREAD

**Issue by Achllle** [ROBOTIS-GIT/hls_lfcd_lds_driver#34]
When launching the driver for the LIDAR:

```
        <node pkg="hls_lfcd_lds_driver"
              type="hlds_laser_publisher"
              name="hlds_laser_publisher"
              output="screen"
              ns="lidar">
            <param name="port" value="/dev/lidar"/>
            <param name="frame_id" value="laser"/>
        </node>
```

Most of the time this works, publishing valid laser scans. However, sometimes it fails with the error:

```
[ERROR] [1536262956.952327969]: An exception was thrown: read: End of file
```

Sometimes just relaunching will work.

**Comment by kijongGil** [comment]
Hi @Achllle :)
I suspect a hardware problem. Has this problem occurred since you first used lds?
If so, please contact us by email at: contactus2@robotis.com

Thanks,
Gilbert

**Comment by Achllle** [comment]
I sent out an email to that address. Thanks

**Comment by kijongGil** [comment]
I'm going to close this issue. If you have a another problem, you can reopen it.
