### ISSUE TITLE
node stops sending data

### ISSUE THREAD

**Issue by mavro10600** [ROBOTIS-GIT/hls_lfcd_lds_driver#35]
Im using the LIDAR with ROS and navigation stack, sometimes (more often lately) it stops sending data through the port as if the communication stopped.

**Comment by kijongGil** [comment]
I think it is a hardware problem is suspected. How about check USB connector or change another LDS?

Thanks,
Gilbert.

**Comment by robotpilot** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
