### ISSUE TITLE
Error when running turtlebot3 bringup 

### ISSUE THREAD

**Issue by alvinisheree** [ROBOTIS-GIT/hls_lfcd_lds_driver#36]
Hi, following the steps in bringup a turtlebot3, I am currently stuck with this error:

pi@raspberrypi:~ $ roslaunch turtlebot3_bringup turtlebot3_robot.launch
... logging to /home/pi/.ros/log/bb0b8944-dc40-11e8-b6d2-48e24421dfbd/roslaunch-raspberrypi-1073.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.100:42113/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /turtlebot3_core/baud: 115200
 * /turtlebot3_core/port: /dev/ttyACM0
 * /turtlebot3_core/tf_prefix: 
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_core (rosserial_python/serial_node.py)
    turtlebot3_diagnostics (turtlebot3_bringup/turtlebot3_diagnostics)
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.1.105:11311

process[turtlebot3_core-1]: started with pid [1082]
process[turtlebot3_lds-2]: started with pid [1083]
process[turtlebot3_diagnostics-3]: started with pid [1084]
[ERROR] [1540906375.858127004]: An exception was thrown: open: No such file or directory
[turtlebot3_lds-2] process has died [pid 1083, exit code 255, cmd /home/pi/catkin_ws/devel/lib/hls_lfcd_lds_driver/hlds_laser_publisher __name:=turtlebot3_lds __log:=/home/pi/.ros/log/bb0b8944-dc40-11e8-b6d2-48e24421dfbd/turtlebot3_lds-2.log].
log file: /home/pi/.ros/log/bb0b8944-dc40-11e8-b6d2-48e24421dfbd/turtlebot3_lds-2*.log
[INFO] [1540906376.792863]: ROS Serial Python Node
[INFO] [1540906376.851901]: Connecting to /dev/ttyACM0 at 115200 baud
[INFO] [1540906379.088580]: Note: publish buffer size is 1024 bytes
[INFO] [1540906379.091671]: Setup publisher on sensor_state [turtlebot3_msgs/SensorState]
[INFO] [1540906379.117068]: Setup publisher on firmware_version [turtlebot3_msgs/VersionInfo]
[INFO] [1540906379.208859]: Setup publisher on imu [sensor_msgs/Imu]
[INFO] [1540906379.228594]: Setup publisher on cmd_vel_rc100 [geometry_msgs/Twist]
[INFO] [1540906379.256692]: Setup publisher on odom [nav_msgs/Odometry]
[INFO] [1540906379.283882]: Setup publisher on joint_states [sensor_msgs/JointState]
[INFO] [1540906379.300244]: Setup publisher on battery_state [sensor_msgs/BatteryState]
[INFO] [1540906379.317624]: Setup publisher on magnetic_field [sensor_msgs/MagneticField]
[INFO] [1540906389.713450]: Setup publisher on /tf [tf/tfMessage]
[INFO] [1540906389.739880]: Note: subscribe buffer size is 1024 bytes
[INFO] [1540906389.741590]: Setup subscriber on cmd_vel [geometry_msgs/Twist]
[INFO] [1540906389.767742]: Setup subscriber on sound [turtlebot3_msgs/Sound]
[INFO] [1540906389.804781]: Setup subscriber on motor_power [std_msgs/Bool]
[INFO] [1540906389.829968]: Setup subscriber on reset [std_msgs/Empty]
[INFO] [1540906389.850336]: Setup TF on Odometry [odom]
[INFO] [1540906389.854633]: Setup TF on IMU [imu_link]
[INFO] [1540906389.858519]: Setup TF on MagneticField [mag_link]
[INFO] [1540906389.862347]: Setup TF on JointState [base_link]
[INFO] [1540906389.883494]: --------------------------
[INFO] [1540906389.887376]: Connected to OpenCR board!
[INFO] [1540906389.891327]: This core(v1.2.3) is compatible with TB3 Burger
[INFO] [1540906389.894822]: --------------------------
[INFO] [1540906389.898775]: Start Calibration of Gyro
[INFO] [1540906392.414749]: Calibration End

I was able to solve this error by changing the USB cable connecting raspberrypi and lidar board yesterday.  However after turning on turtlebot3 again, this error cannot be eradicated and I cannot seem to find out why. Please help. Thank you.

**Comment by routiful** [comment]
Hi :)

Can you test that catkin_make again after remove devel and build folder? (Need `source ~/.bashrc` command)
And launch `turtlebot3_lidar` only not `turtlebot3_robot`

**Comment by alvinisheree** [comment]
Hi there!

Sorry I don’t really understand as I am still kind of new to this.. do you mean to execute this command?
$ cd ~/catkin_ws/
$ rm -rf src/ build/ devel/
$ mkdir src
$ cd ~/catkin_ws/src
$ git clone https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver.git
$ git clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
$ git clone https://github.com/ROBOTIS-GIT/turtlebot3.git

**Comment by alvinisheree** [comment]
### Input command:
pi@raspberrypi:~ $ cd ~/catkin_ws/
pi@raspberrypi:~/catkin_ws $ rm -rf build/ devel/
pi@raspberrypi:~/catkin_ws $ source /opt/ros/kinetic/setup.bash
pi@raspberrypi:~/catkin_ws $ cd ~/catkin_ws && catkin_make -j1

### catkin_ws build was successful with no errors.

### Input code to launch lidar:
`pi@raspberrypi:~` $ roslaunch turtlebot3_bringup `turtlebot3_lidar.launch`

### Output:
`... logging to /home/pi/.ros/log/8e82c4de-dce3-11e8-9630-3065ec8d1b60/roslaunch-raspberrypi-2884.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.100:34627/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /turtlebot3_lds/frame_id: base_scan
 * /turtlebot3_lds/port: /dev/ttyUSB0

NODES
  /
    turtlebot3_lds (hls_lfcd_lds_driver/hlds_laser_publisher)

ROS_MASTER_URI=http://192.168.1.105:11311

process[turtlebot3_lds-1]: started with pid [2893]
[ERROR] [1540974585.664563059]: An exception was thrown: open: No such file or directory
[turtlebot3_lds-1] process has died [pid 2893, exit code 255, cmd /home/pi/catkin_ws/devel/lib/hls_lfcd_lds_driver/hlds_laser_publisher __name:=turtlebot3_lds __log:=/home/pi/.ros/log/8e82c4de-dce3-11e8-9630-3065ec8d1b60/turtlebot3_lds-1.log].
log file: /home/pi/.ros/log/8e82c4de-dce3-11e8-9630-3065ec8d1b60/turtlebot3_lds-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by routiful** [comment]
Sorry for inconvenience, Can you please test it without ROS?
I give you a reference how to run it

http://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_lds_01/#user-guide-for-driver

**Comment by alvinisheree** [comment]
Hi, I was able to solve the problem by changing the cable connecting LIDAR to Raspberry Pi.
Now I am currently stuck with another problem at step 9, SLAM. When i ran this command:
`roslaunch turtlebot3_slam turtlebot3_slam.launch slam_methods:=gmapping` in RVIZ, I am unable to see any image produced by LIDAR where the status says "No image received". Do you know how to solve this issue? Please help thank you.

**Comment by alvinisheree** [comment]
This issue persisted even at step 11: Simulation where i ran turtlebot3 simulation in gazebo and after launching command to open RVIZ: `roslaunch turtlebot3_gazebo turtlebot3_gazebo_rviz.launch` the camera does not display any image as well. Is there something wrong with my currently installed RVIZ package or is there problem somewhere else. I tried googling around but couldn't find any solution for this problem.

**Comment by routiful** [comment]
Sorry for late reply.
TB3 burger doesn't have a camera. If you want to show image, you are supposed to install camera on your TB3.

**Comment by gpwhd07** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
