### ISSUE TITLE
An exception was thrown: read: End of file 

### ISSUE THREAD

**Issue by bansallovish** [ROBOTIS-GIT/hls_lfcd_lds_driver#39]
I am using LIDAR LDS01 with Raspberry Pi 3 model B with Ubuntu Mate with ROS Kinetic
When i run the command : 
`roslaunch hls_lfcd_lds_driver view_hlds_laser.launch`

It gives this error : 
```
[ERROR] [.......]: An exception was thrown: read: End of file
libEGL warning: DRI2: failed to authenticate
[hlds_laser_publisher-2] process has died [......]
log file: /home/.......log
```

But, when i connected the same LIDAR with my Ubuntu 16.04 PC, it worked fine

**Comment by ROBOTIS-Kayman** [comment]
I think it's library problem of ubuntu mate.
Could you re-install ubuntu mate?

**Comment by bansallovish** [comment]
Is there any other solution ?
Because ROS will take so much time to install and also i will have to take a backup of the files in Raspberry Pi.

**Comment by ROBOTIS-Kayman** [comment]
Unfortunately, I do not know any other solution.

**Comment by ROBOTIS-Kayman** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.

**Comment by TrendMend** [comment]
Any updates? I have the same issue I am afraid...
