### ISSUE TITLE
Not able to Bring up Turtlebot3 in ROS kinetic/Ubuntu 16.04LTS after installing the packages many times.......The output [turtlebot3_lidar.launch] is neither a launch file in package [turtlebot3_bringup] nor is [turtlebot3_bringup] a launch file name The traceback for the exception was written to the log file

### ISSUE THREAD

**Issue by dhruvtalwar01** [ROBOTIS-GIT/hls_lfcd_lds_driver#40]

**Comment by dhruvtalwar01** [comment]
[turtlebot3_lidar.launch] is neither a launch file in package [turtlebot3_bringup] nor is [turtlebot3_bringup] a launch file name
The traceback for the exception was written to the log file

**Comment by RyanJaehyunShim** [comment]
@dhruvtalwar01 

Would you explain which tutorial you are working on now? 

Follow the following link, and download and install TB3 packages first.
(http://emanual.robotis.com/docs/en/platform/turtlebot3/pc_setup/#install-ubuntu-on-remote-pc)

If you still get the same error message, type below and try it again.
$ rospack profile

If you don't know well how to use ROS, I recommend you study ROS tutorial at the link below.
(http://wiki.ros.org/ROS/Tutorials)

Regards,
Ryan

**Comment by dhruvtalwar01** [comment]
Thank you Ryan. The tutorials were from a book.
I added the packages it now works fine.( I also re installed ROS)
