### ISSUE TITLE
Can configure this laser on other robots?

### ISSUE THREAD

**Issue by houhaol** [ROBOTIS-GIT/hls_lfcd_lds_driver#66]
Hello,

I was wondering how to install this laser on other robots, besides turtlebot3. I installed as these steps
`sudo apt-get install ros-melodic-hls-lfcd-lds-driver`
 `sudo chmod a+rw /dev/ttyUSB0`
`roslaunch hls_lfcd_lds_driver view_hlds_laser.launch`

But no laser data output. The status of LaserScan is ok in rviz.

I tried 
`rostopic echo /scan`
still has not received data. 

Can you help me about this? Is it possible to configure on other robots?

Thanks a lot for your help.

**Comment by ROBOTIS-Will** [comment]
Hi @houhaol 
First of all, make sure that your PC is assigned ttyUSB0 to the Lidar sensor.
In order to run the RViz, you should launch the hlds_laser_publisher node first as described in [the eManual](https://emanual.robotis.com/docs/en/platform/turtlebot3/appendix_lds_01/#run-hlds_laser_publisher-node).
```
$ roslaunch hls_lfcd_lds_driver hlds_laser.launch
```
Thanks

**Comment by houhaol** [comment]
Hi @ROBOTIS-Will 
thanks for your reply. I directly connected this lidar on my raspberry pi board and assigned it as `sudo chmod a+rw /dev/ttyUSB0` or `sudo chmod a+rw /dev/ttyUSB1` . But looks like it failed on my raspberry board.  

Then I tried it on my pc which works. possible to do it on raspberry board?

Thanks

**Comment by ROBOTIS-Will** [comment]
You mean you have connected lidar without the USB2LDS interface?
![](https://emanual.robotis.com/assets/images/platform/turtlebot3/appendix_lds/lds_lines.png)
This driver package is developed for the use with USB2LDS.
In order to directly connect the sensor to Raspberry Pi GPIO, you should modify the source code.

If you were using USB2LDS to connect the sensor to Raspberry Pi, please describe each step to reproduce your issue from installing the package to launching the sensor nodes.
Thanks.

**Comment by houhaol** [comment]
sorry. I'm a newbie in this area. I think i use  USB2LDS. The USB cable to raspberry USB Port. Then run the following in my raspberry ubuntu terminals. 

one terminal for roscore
one for 
sudo apt-get install ros-melodic-hls-lfcd-lds-driver
sudo chmod a+rw /dev/ttyUSB0
roslaunch hls_lfcd_lds_driver view_hlds_laser.launch

**Comment by ROBOTIS-Will** [comment]
@houhaol 
After installing and setting up the ttyUSB0 port, the correct step to launch the sensor and check the sensor output on RViz would be
```
$ roslaunch hls_lfcd_lds_driver hlds_laser.launch
```
Open a new terminal and enter below command
```
$ roslaunch hls_lfcd_lds_driver view_hlds_laser.launch
```

**Comment by houhaol** [comment]
Hi @ROBOTIS-Will ,
No. These two commands are in conflict. It will shut down the old one since new node registered with same name. 

> roslaunch hls_lfcd_lds_driver hlds_laser.launch
> ... logging to /home/ubuntu/.ros/log/a46c6242-aefe-11eb-a1d9-dca6328895ca/roslaunch-ubuntu-4586.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://192.168.3.10:40599/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /hlds_laser_publisher/frame_id: laser
>  * /hlds_laser_publisher/port: /dev/ttyUSB0
>  * /rosdistro: melodic
>  * /rosversion: 1.14.10
> 
> NODES
>   /
>     hlds_laser_publisher (hls_lfcd_lds_driver/hlds_laser_publisher)
> 
> ROS_MASTER_URI=http://192.168.3.10:11311
> 
> process[hlds_laser_publisher-1]: started with pid [4601]
> [ WARN] [1620369507.280979712]: Shutdown request received.
> [ WARN] [1620369507.290325435]: Reason given for shutdown: [[/hlds_laser_publisher] Reason: new node registered with same name]
> [hlds_laser_publisher-1] process has finished cleanly
> log file: /home/ubuntu/.ros/log/a46c6242-aefe-11eb-a1d9-dca6328895ca/hlds_laser_publisher-1*.log
> all processes on machine have died, roslaunch will exit
> shutting down processing monitor...
> ... shutting down processing monitor complete
> done
> 

The other one:

> ubuntu@ubuntu:~$ roslaunch hls_lfcd_lds_driver view_hlds_laser.launch
> ... logging to /home/ubuntu/.ros/log/a46c6242-aefe-11eb-a1d9-dca6328895ca/roslaunch-ubuntu-4703.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://192.168.3.10:45135/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /hlds_laser_publisher/frame_id: laser
>  * /hlds_laser_publisher/port: /dev/ttyUSB0
>  * /rosdistro: melodic
>  * /rosversion: 1.14.10
> 
> NODES
>   /
>     hlds_laser_publisher (hls_lfcd_lds_driver/hlds_laser_publisher)
>     rviz (rviz/rviz)
> 
> ROS_MASTER_URI=http://192.168.3.10:11311
> 
> process[hlds_laser_publisher-1]: started with pid [4743]
> [ WARN] [1620369507.294321523]: Shutdown request received.
> [ WARN] [1620369507.327130171]: Reason given for shutdown: [[/hlds_laser_publisher] Reason: new node registered with same name]
> process[rviz-2]: started with pid [4749]
> libEGL warning: DRI2: failed to authenticate
> 

I tried it on my PC. It worked but failed on my raspberry. Quite weird
