### ISSUE TITLE
[ROS-Humble] Can't run the launch file view_hlds_laser.launch.py 

### ISSUE THREAD

**Issue by AnhHazz** [ROBOTIS-GIT/hls_lfcd_lds_driver#74]
I installed the ros-humble-hls-lfcd-lds-driver to run lds-01. I tried to complie the .cpp file and it worked, it show to terminal this : 
`r[359]=0.236000,r[358]=0.221000,r[357]=0.217000,r[356]=0.214000,r[355]=0.211000,r[354]=0.209000,r[353]=0.208000,r[352]=0.206000,r[351]=0.204000,r[350]=0.202000,r[349]=0.200000,r[348]=0.199000,r[347]=0.198000,r[346]=0.196000,r[345]=0.195000,r[344]=0.194000,r[343]=0.145000,r[342]=0.193000,r[359]=0.236000,r[358]=0.221000,r[357]=0.217000,r[356]=0.214000,r[355]=0.211000,r[354]=0.209000,r[359]=0.019000,r[358]=0.019000,r[357]=0.019000,r[356]=0.019000,r[355]=0.019000,r[354]=0.019000,r[359]=0.235000,r[358]=0.221000,r[357]=0.217000,r[356]=0.214000,r[355]=0.211000,r[354]=0.209000,r[353]=0.208000,r[352]=0.206000,r[351]=0.204000,r[350]=0.202000,r[349]=0.200000,r[348]=0.199000,r[347]=0.198000,r[346]=0.196000,r[345]=0.159000,r[344]=45.250000,r[343]=0.225000,r[342]=0.195000,r[359]=43.008000,r[358]=54.528000,r[357]=47.104000,r[356]=63.488000,r[355]=43.776000,r[354]=29.184000,r[359]=0.236000,r[358]=0.221000,r[357]=0.217000,r[356]=0.214000,r[355]=0.211000,r[354]=0.209000,r[353]=0.208000,r[352]=0.206000,r[351]=0.204000,`

This seem the lds01 still work.

Then i tried to run the launch files, the ` ros2 launch hls_lfcd_lds_driver hlds_laser.launch.py` and `ros2 launch hls_lfcd_lds_driver view_hlds_laser.launch.py `. That when rviz show the error 
`ViewController ‘Current View'unavailable.

The class required for this view controller, ‘rviz/Orbit’, could not be loaded.

Error:

According to the loaded plugin descriptions the class rviz/
Orbit with base class type rviz_common:ViewController
does not exist. Declared types are rviz_default_plugins/FPS
viz_default_plugins/Orbit rviz_default_plugins/
ThirdPersonFollower rviz_default_plugins/TopDownOrtho
viz_default_plugins/XYOrbit
`
I installed all rviz files but can't fix this.
Tks for reading!

**Comment by thebigboss84** [comment]
Same here with ROS2 foxy

**Comment by AnhHazz** [comment]
> +1, having the same problem on ROS2 Humble



> Same here with ROS2 foxy. I can see the values when echo /scan but for some reason can't see them on RVIz2

I found out that the problem is in the rviz file, so i have modified it and now it worked. Here is the RViz2 config file: [https://drive.google.com/file/d/1nBtFphFQ0qiiFUDT1cZczV_hJLiy3Ocs/view?usp=drive_link](url)

The result is: 
[Screencast from 12-11-2023 02:29:30 PM.webm](https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver/assets/137688616/8d7022fd-ec23-4671-8be7-88ea0c7d0541)

It seem like my lds-01 has problem with the connect wires since the points showing are not stable althought it's not moving at all

**Comment by thebigboss84** [comment]
I was able to make my LiDAR work only by launching the launch file and not view, launched RVIZ2 and changed the reliability to best effort 
Increased the points size and viola I was able to see the scans

**Comment by AnhHazz** [comment]
> I was able to make my LiDAR work only by launching the launch file and not view, launched RVIZ2 and changed the reliability to best effort Increased the points size and viola I was able to see the scans

Can you share your result? I think mine is broken.
